### ISSUE TITLE
Some problems to run the code

### ISSUE THREAD

**Issue by zhiqiangzhongddu** [XiaoxinHe/TAPE#10]
Hi,

Thanks for the nice work and sharing the code. 
I'm trying to run your code but have some problems. 

1. When I run`WANDB_DISABLED=True TOKENIZERS_PARALLELISM=False CUDA_VISIBLE_DEVICES=0,1 python -m core.trainLM dataset cora seed 0 >> cora_lm.out`, I got data missing error: `FileNotFoundError: [Errno 2] No such file or directory: 'dataset/cora_orig/mccallum/cora/extractions/http:##www.cs.ucl.ac.uk#staff#t.yu#ep97.ps'`
2. When I run `WANDB_DISABLED=True TOKENIZERS_PARALLELISM=False CUDA_VISIBLE_DEVICES=0,1 python -m core.trainLM dataset ogbn-arxiv seed 0 >> ogbn-arxiv_lm.out`, I got `File "/home/xxx/TAPE/core/data_utils/load_arxiv.py", line 24, in get_raw_text_arxiv
    data.edge_index = data.adj_t.to_symmetric()
AttributeError: 'Tensor' object has no attribute 'to_symmetric'`. I guess it's because of the OGB version conflict, could you tell me your OGB version or update your code? My OGB version is 1.3.6.

**Comment by zhiqiangzhongddu** [comment]
Hi,

Thanks for your prompt answers. 

Question #2 disappeared after re-setting up the environment. 

However, Question #1 is still the same as before. I downloaded everything on 07/12, thus I think it should be the latest uploaded version. 
I manually checked the file and found that: 
1. There are two similar items in dataset/cora_orig/mccallum/cora/papers: "http:##www.cs.ucl.ac.uk#staff#T.Yu#ep97.ps" and "http:##www.cs.ucl.ac.uk#staff#t.yu#ep97.ps". 
2. At the folder dataset/cora_orig/mccallum/cora/extractions/, there is one file "http/##www.cs.ucl.ac.uk#staff#T.Yu#ep97.ps" but not "http/##www.cs.ucl.ac.uk#staff#t.yu#ep97.ps". 

Hope it helps.

**Comment by XiaoxinHe** [comment]
Hi,

Sorry for the late reply. Could you please check if the discussions in  #5  are helpful?

**Comment by ChenS676** [comment]
hallo I also have this issue in the linux system, I think it is essentially caused by the invisible setting of the path extraction. I can paste my code here, hopefully, it helps! It already works for me with the current version of the dataset. @zhiqiangzhongddu 

`def parse_cora():
    path = root_path + 'dataset/cora_orig/cora'
    idx_features_labels = np.genfromtxt(
        "{}.content".format(path), dtype=np.dtype(str))
    data_X = idx_features_labels[:, 1:-1].astype(np.float32)
    labels = idx_features_labels[:, -1]
    class_map = {x: i for i, x in enumerate(['Case_Based', 'Genetic_Algorithms', 'Neural_Networks',
                                            'Probabilistic_Methods', 'Reinforcement_Learning', 'Rule_Learning', 'Theory'])}
    data_Y = np.array([class_map[l] for l in labels])
    data_citeid = idx_features_labels[:, 0]
    idx = np.array(data_citeid, dtype=np.dtype(str))
    idx_map = {j: i for i, j in enumerate(idx)}
    edges_unordered = np.genfromtxt(
        "{}.cites".format(path), dtype=np.dtype(str))
    edges = np.array(list(map(idx_map.get, edges_unordered.flatten()))).reshape(
        edges_unordered.shape)
    data_edges = np.array(edges[~(edges == None).max(1)], dtype='int')
    data_edges = np.vstack((data_edges, np.fliplr(data_edges)))
    return data_X, data_Y, data_citeid, np.unique(data_edges, axis=0).transpose()


def get_raw_text_cora(use_text=False, seed=0):
    data, data_citeid = get_cora_casestudy(seed)
    if not use_text:
        return data, None

    with open('dataset/cora_orig/mccallum/cora/papers')as f:
        lines = f.readlines()
    pid_filename = {}
    for line in lines:
        pid = line.split('\t')[0]
        fn = line.split('\t')[1]
        pid_filename[pid] = fn

    path = 'dataset/cora_orig/mccallum/cora/extractions/'
    # path = 'dataset/cora/extractions/'
    values = os.listdir(path)
    with open("extraction.txt", 'w') as output:
        for row in values:
            output.write(str(row) + '\n')
            
    text = []
    not_loaded = []
    i = 0
    for pid in data_citeid:
        fn = pid_filename[pid]
        try:
            if os.path.exists(path+fn): 
                pathfn = path+fn
            elif os.path.exists(path+fn.replace(":", "_")):
                pathfn = path+fn.replace(":", "_")
            elif os.path.exists(path+fn.replace("_", ":")):
                pathfn = path+fn.replace("_", ":")
                
            with open(pathfn) as f:
                lines = f.read().splitlines()
                    
            for line in lines:
                if 'Title:' in line:
                    ti = line
                if 'Abstract:' in line:
                    ab = line
            text.append(ti+'\n'+ab)
        except:
            not_loaded.append(pathfn)
            i += 1

        # print(f"not loaded {i} papers.")
        # print(f"not loaded papers: {not_loaded}")
    return data, text`
