### ISSUE TITLE
There are some missing titles and abstracts in Cora data

### ISSUE THREAD

**Issue by MarchenCreator** [XiaoxinHe/TAPE#12]
Hi！Thank you for your open source and excellent work！
![image](https://github.com/XiaoxinHe/TAPE/assets/82066669/feb26609-b959-405f-98df-646b09936b4b)
But I found that the title and abstract in some of the Cora data you provided are missing. Is this the issue I dealt with?

**Comment by XiaoxinHe** [comment]
Hi,

Thank you for your interest in our work and for bringing this issue to our attention.

Yes, there are instances where the title or abstract in the Cora dataset is incomplete or missing. This could be attributed to potential errors during the data crawling process. It's important to note that only a small number of data samples are affected, and this should not impact the overall versatility of the dataset or the effectiveness of the associated methods.

If you have any further questions or concerns, please feel free to let us know.

**Comment by MarchenCreator** [comment]
Thank you very much for your reply！ Perhaps using complete information fine-tuning to generate incomplete parts seems to be a good choice.
