### ISSUE TITLE
Missing files in gnnkd/textual_datasets/dataset/cora_orig/mccallum/cora/extractions

### ISSUE THREAD

**Issue by lxer19** [XiaoxinHe/TAPE#13]
https://github.com/XiaoxinHe/TAPE/blob/1821dddfd030793ecbe10e6f32f0476e0cb671c4/core/data_utils/load_cora.py#L93
I got issues when trying to rerun the load_cora.py files, the issue is "FileNotFoundError: [Errno 2] No such file or directory: 'gnnkd/textual_datasets/dataset/cora_orig/mccallum/cora/extractions/http:##www.daimi.aau.dk#~brian#japan97.ps'"

It seems that the cora_orig file is missing some files

**Comment by DiligentDing** [comment]
Hi,it seems that I meets the same missing file problem.How do you sovle it?

**Comment by nxlogn** [comment]
me, too. have you solved it?
