### ISSUE TITLE
Could you please provide the code constructing the subgraph?

### ISSUE THREAD

**Issue by 1957787636** [XiaoxinHe/TAPE#16]
Hi, in the paper, you mentioned constructing the subset of ogbn-products dataset, but  I don't  find the code of the above function, could you please provide the code?

Thank you!

**Comment by XiaoxinHe** [comment]
I didn't save the code used for constructing the subset of the ogbn-products dataset. Just for your reference, I remember using the `NeighborLoader` to sample nodes until I obtained the desired number of nodes.

```
subgraph_loader = NeighborLoader(
    data,
    input_nodes=input_nodes,
    num_neighbors=[15, 10, 5],
    batch_size=1024,
    shuffle=True,
    num_workers=4
)
```

**Comment by 1957787636** [comment]
thank your reply!
