### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by TrungTechh** [XiaoxinHe/TAPE#2]
Seem like you haven't uploaded the full file yet. When i training the GNNs

`python -m core.trainEnsemble gnn.model.name GCN`

It causes error ``No such file or directory: 'prt_lm/cora/microsoft/deberta-base-seed0.emb'`` 
at  line 47 in `gnn_trainer.py`

**Comment by XiaoxinHe** [comment]
Please refer to 4. Reproducibility in the README.md file.

You can either 
1) train the language model (LM) by yourself, follow the instructions provided in the run.sh file ([line 5 and line 6](https://github.com/XiaoxinHe/TAPE/blob/241c93b735dcebbe2853414395c1559d5c2ce202/run.sh#L5C1-L6)).
or
2) download our trained LMs [here](https://drive.google.com/drive/folders/1nF8NDGObIqU0kCkzVaisWooGEQlcNSIN).

**Comment by XiaoxinHe** [comment]
We would like to inform you that the issue you reported has been resolved, and we are now closing it. If you have any further questions or need additional assistance, please don't hesitate to reach out to us.
