### ISSUE TITLE
About the accuracy of LLM predictions

### ISSUE THREAD

**Issue by MasterofPLM** [XiaoxinHe/TAPE#3]
Hi Xiaoxin. In the paper, the topK LLM predictions are used as node features. Do we have ablation study on the accuracy of the LLM predictions? Thanks a lot!

**Comment by XiaoxinHe** [comment]
Hi, 

Yes, we have the ablation study on the accuracy of the LLM prediction.

1) LM (top-1 accuracy). This refers to the top-1 accuracy of the LLM predictions. In Table 1 of the paper, you can find the LLM column with corresponding values for different datasets:
- Cora: Top-1 accuracy of 0.6769
- PubMed: Top-1 accuracy of 0.9342
- OGBN-Arxiv: Top-1 accuracy of 0.7350

2) LM+GNN. This represents the combination of LM and GNN by using the top-k LLM predictions as the node features. The results are shown in Table 2 of the paper under the $f_{pred}$ column.

If you have any further questions or need more clarification, feel free to ask!

**Comment by pricexu** [comment]
Hi Xiaoxin,

Thanks for this interesting work. I was checking the acc of the LLM's prediction using your provided data in "gpt_preds" However, the acc I tested is different from what you replied. My following piece of code is used, where I copied your load_gpt_preds function:
```
def load_gpt_preds(folder, dataset):
    preds = []
    fn = f"{folder}/{dataset}.csv"
    with open(fn, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            inner_list = []
            for value in row:
                inner_list.append(int(value))
            preds.append(inner_list)
    return preds

folder = "/MY_FOLDER/TAPE/gpt_preds"
datasets = ['cora', 'pubmed', 'ogbn-arxiv', 'ogbn-products', 'arxiv_2023']
for dataset in datasets:
    _, data = load_data(dataset, 'MY_ROOT_FOLDER') # this is the loading data function from OGB
    gt = data.y.flatten().tolist()
    for topk in range(1, 4):
        preds = load_gpt_preds(folder, dataset)
        preds = [x[:topk] for x in preds]
        assert len(preds) == len(gt)
        acc = sum([1 for i in range(len(gt)) if gt[i] in preds[i]]) / len(gt)
        print(f"Dataset: {dataset}, Top-{topk} Accuracy: {acc:.4f}")
```

and what I see is
```
Dataset: cora, Top-1 Accuracy: 0.1721
Dataset: cora, Top-2 Accuracy: 0.2430
Dataset: cora, Top-3 Accuracy: 0.2489
Dataset: pubmed, Top-1 Accuracy: 0.3645
Dataset: pubmed, Top-2 Accuracy: 0.3965
Dataset: pubmed, Top-3 Accuracy: 0.3980
Dataset: ogbn-arxiv, Top-1 Accuracy: 0.7350
Dataset: ogbn-arxiv, Top-2 Accuracy: 0.8756
Dataset: ogbn-arxiv, Top-3 Accuracy: 0.9240
Dataset: ogbn-products, Top-1 Accuracy: 0.7440
Dataset: ogbn-products, Top-2 Accuracy: 0.8513
Dataset: ogbn-products, Top-3 Accuracy: 0.8921
Dataset: arxiv_2023, Top-1 Accuracy: 0.7356
Dataset: arxiv_2023, Top-2 Accuracy: 0.8830
Dataset: arxiv_2023, Top-3 Accuracy: 0.9289
```

I think the acc on ogbn-arxiv matches what you reported, but the accs on Cora and Pubmed are much lower than the numbers you said 0.6769 and 0.9342. 

I am wondering if the file "cora.csv" and "pubmed.csv" is wrong , could you help have a very quick check? I would greatly appreciate that!

Zhe
