### ISSUE TITLE
Problem in  the data loading~ 

### ISSUE THREAD

**Issue by AA-OPO** [XiaoxinHe/TAPE#4]
Thanks for your great work!

when I run the command
```
WANDB_DISABLED=True TOKENIZERS_PARALLELISM=False CUDA_VISIBLE_DEVICES=0 python -m core.trainLM dataset cora
```
I encountered a data loading error:
```
 File "/home/TAPE/core/data_utils/load_cora.py", line 93, in get_raw_text_cora
    with open(path+fn) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/cora_orig/mccallum/cora/extractions/http:##www.sdsc.edu#~tbailey#papers#ismb96.ps'
```

**Comment by XiaoxinHe** [comment]
Hi,

To resolve this, you'll need to download the dataset first. Here's how you can do it for the cora dataset:
1. Download the cora dataset from [this link](https://drive.google.com/file/d/1oo6EbCjrwOabjjudT5LGx75Ks9_HBAMs/view?usp=sharing).
2. After downloading, unzip the dataset.
3. Move the unzipped dataset folder to the following directory: dataset/cora_orig.

For more detailed instructions, you can refer to "1. Download TAG datasets" in the readme file of the project.

This should hopefully resolve the data loading issue. If you encounter any further problems, please don't hesitate to ask for assistance.

Thanks!

**Comment by ChenS676** [comment]
I have followed the 

> Hi,
> 
> To resolve this, you'll need to download the dataset first. Here's how you can do it for the cora dataset:
> 
> 1. Download the cora dataset from [this link](https://drive.google.com/file/d/1oo6EbCjrwOabjjudT5LGx75Ks9_HBAMs/view?usp=sharing).
> 2. After downloading, unzip the dataset.
> 3. Move the unzipped dataset folder to the following directory: dataset/cora_orig.
> 
> For more detailed instructions, you can refer to "1. Download TAG datasets" in the readme file of the project.
> 
> This should hopefully resolve the data loading issue. If you encounter any further problems, please don't hesitate to ask for assistance.
> 
> Thanks for the reply. I have followed the blog above but still have this issue. Could it be possible to share the updated dataset again or provide a load data ipynb?
