### ISSUE TITLE
Missing .ps file for Cora Dataset

### ISSUE THREAD

**Issue by ChenS676** [XiaoxinHe/TAPE#5]
Here's a polished version of your message to report issues on another researcher's GitHub repo:

---

Dear Mr. He,

Firstly, I'd like to express my gratitude for sharing the code related to your remarkable research. I've encountered an issue during the reconstruction process. Specifically, I couldn't locate certain papers in the "extraction" folder. 

Could you please let me know if there's an updated version of the Cora dataset available for public use? Alternatively, I might have misunderstood the instructions provided in the README.md.

To replicate the issue I faced, you can run the following code:

```python
if __name__ == '__main__':
    data, data_citeid = get_cora_casestudy()
    data, text = get_raw_text_cora(use_text=True)
    print(data)
    print(data_citeid)
```

Executing the above should help you reproduce the error I encountered. 

Thank you for your time and assistance.

Best regards,
[Your Name]

---

This version is more concise and structured, making it easier for the recipient to understand and address your concerns.

**Comment by XiaoxinHe** [comment]
Hi,

To resolve this, you'll need to download the dataset first. Here's how you can do it for the cora dataset:

Download the cora dataset from [this link](https://drive.google.com/file/d/1oo6EbCjrwOabjjudT5LGx75Ks9_HBAMs/view?usp=sharing).
After downloading, unzip the dataset.
Move the unzipped dataset folder to the following directory: dataset/cora_orig.
For more detailed instructions, you can refer to "1. Download TAG datasets" in the readme file of the project.

This should hopefully resolve the data loading issue. If you encounter any further problems, please don't hesitate to ask for assistance.

Thanks!

**Comment by ChenRunjin** [comment]
Hi, I also met this problem, I've followed the instructions above, download the datasets and move it to the right position. But the problem still exists,  it seems that  some files in */extraction/* have mismatched formats, so we can't unzip them.

**Comment by ChenS676** [comment]
I think XiaoxiHe answered before in this Email, 
"
Thank you for the detailed description of the issue.

I would like to clarify that our dataset is available in two distinct variations: one for the original text attributes(i.e., title and abstract), another for the LLM responses (i.e., prediction and explanation).
[link1] cora + original text attributes: https://drive.google.com/file/d/1oo6EbCjrwOabjjudT5LGx75Ks9_HBAMs/view 
[link2] cora + LLM responses: https://drive.google.com/file/d/1tSepgcztiNNth4kkSR-jyGkNnN7QDYax/view
Based on your description, it appears that you are attempting to load the dataset with the original text attributes. If this is indeed the case, please make sure to use link1 for the download rather than link2.

I redownloaded the dataset with link 1 and ran the code below.
" 
at least it works for me. 

to be honest three datasets sounds not enough to prove the concept, if you have found other text-attributed graph, let me know Mr/Ms. ChenRunJin?

**Comment by ZhuYun97** [comment]
> Hi, I also met this problem, I've followed the instructions above, download the datasets and move it to the right position. But the problem still exists, it seems that we need to replace ':' to '_' of fn

For Cora dataset, there are three special cases that typically require specific processing steps when loading original texts:
```
fn = fn.replace(':', '_')
if fn == 'http_##www.cs.ucc.ie#~dgb#papers#ICCBR2.ps.Z':
    fn = 'http_##www.cs.ucc.ie#~dgb#papers#iccbr2.ps.Z'
if fn == 'http_##www.cs.ucl.ac.uk#staff#t.yu#ep97.ps':
    fn = 'http_##www.cs.ucl.ac.uk#staff#T.Yu#ep97.ps'
if fn == 'http_##www.cs.ucl.ac.uk#staff#t.yu#pgp.new.ps':
    fn = 'http_##www.cs.ucl.ac.uk#staff#T.Yu#pgp.new.ps'
```
Adding these codes after [this line](https://github.com/XiaoxinHe/TAPE/blob/7d9bfba751422a59d63f281fa5d665b1ebcc104f/core/data_utils/load_cora.py#L86).

**Comment by XiaoxinHe** [comment]
Hi,

I've uploaded an updated version of the cora dataset that should resolve the issue. You can now download it with the corrected filename format. Let me know if you encounter any more problems.
