### ISSUE TITLE
The issue of inconsistent data splits in ‘ensemble_trainer.py’.

### ISSUE THREAD

**Issue by LarFii** [XiaoxinHe/TAPE#7]
Within ‘ensemble_trainer.py’, the absence of a set seed in ‘load_data’ could lead to inconsistencies between the data split during the training process and the data split during the final ensemble evaluation.
![image](https://github.com/XiaoxinHe/TAPE/assets/49157727/8c69e483-4acc-40f3-bab8-a6176cda09b8)

**Comment by LarFii** [comment]
It may lead to data leakage during training, resulting in inflated performance metrics.

**Comment by XiaoxinHe** [comment]
Thank you for bringing this to our attention. We've addressed the issue you mentioned in [this commit](https://github.com/XiaoxinHe/TAPE/commit/7d9bfba751422a59d63f281fa5d665b1ebcc104f).

It's worth noting that for the ogbn-arxiv dataset, the data split isn't influenced by the seed value. Therefore, any inconsistencies between the data split during the training process and the final ensemble evaluation should not impact the results for this specific dataset.

However, for other datasets, we are currently in the process of rerunning the experiments, and we will promptly update the results accordingly.

Thanks again for pointing out this issue.

**Comment by XiaoxinHe** [comment]
<img width="1407" alt="Screenshot 2023-10-11 at 20 46 48" src="https://github.com/XiaoxinHe/TAPE/assets/48676630/35e590e8-c0e8-4f1b-923f-d1964cab98e1">
