### ISSUE TITLE
How to download OGBN-Products(subset)

### ISSUE THREAD

**Issue by ZhuYun97** [XiaoxinHe/TAPE#9]
The README.md does not contain the links for downloading OGBN-Products(subset) dataset. Could you please provide it if available?

**Comment by pornosaur** [comment]
Same question: where to get raw text for ogbn-products?

**Comment by XiaoxinHe** [comment]
Sure. You can find the ogbn-products(subset) dataset using the following links: 

- Raw text (title and abstract): [ogbn-products_subset.csv](https://github.com/XiaoxinHe/TAPE/blob/main/dataset/ogbn_products_orig/ogbn-products_subset.csv)
- GPT responses (predictions and explanations): [Download here](https://drive.google.com/file/d/1C769tlhd8pT0s7I3vXIEUI-PK7A4BB1p/view)

Please check the updated README.md file for more instructions. Thanks!
